// svelte-microfrontend/src/Navbar.svelte
<script>
    import { push } from 'svelte-spa-router';
    
    function navigateTo(route) {
      push(route);
    }
  </script>
  
  <nav>
    <ul>
      <li><a href="/svelte-microfrontend/src/Signup.svelte" on:click|preventDefault={() => navigateTo('/signup')}>Sign Up</a></li>
      <li><a href="/svelte-microfrontend/src/Signup.svelte" on:click|preventDefault={() => navigateTo('/signin')}>Sign In</a></li>
    </ul>
  </nav>
  
  <style>
    nav {
      background-color: #333;
      padding: 10px;
    }
  
    ul {
      list-style: none;
      padding: 0;
      margin: 0;
      display: flex;
      justify-content: center;
    }
  
    li {
      margin: 0 15px;
    }
  
    a {
      color: white;
      text-decoration: none;
      font-size: 16px;
    }
  
    a:hover {
      text-decoration: underline;
    }
  </style>

// host-app/src/NavBar.vue
<!-- src/components/NavBar.vue -->
<template>
    <nav>
      <ul>
        <li><router-link to="/">Home</router-link></li>
        <li><router-link to="/cart">Cart</router-link></li>
        <li><router-link to="/filter">Filter</router-link></li>
        <li><router-link to="/search">Search</router-link></li>
        <li><router-link to="/signin">Sign In</router-link></li>
        <li><router-link to="/signup">Sign Up</router-link></li>
      </ul>
    </nav>
  </template>
  
  <script>
  export default {
    name: 'NavBar',
  };
  </script>
  
  <style scoped>
  nav {
    background-color: #333;
    color: white;
    padding: 1rem;
  }
  
  ul {
    list-style: none;
    padding: 0;
    display: flex;
    gap: 1rem;
  }
  
  li {
    margin: 0;
  }
  
  a {
    color: white;
    text-decoration: none;
  }
  
  a.router-link-active {
    font-weight: bold;
  }
  </style>
